### ISSUE TITLE
while VM destroy action perform

### ISSUE THREAD

**Issue by vijaykanthm28** [megamsys/opennebula-go#34]
time="2016-01-19T15:02:23+05:30" level=debug msg="\x1b[1;34;10m > one-go SUCCESS\x1b[0m" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8579e7]

goroutine 214 [running]:
github.com/megamsys/opennebula-go/compute.(*VirtualMachine).Delete(0xc82058f2a0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/megam/.go/src/github.com/megamsys/opennebula-go/compute/compute.go:95 +0x447
github.com/megamsys/megamd/provision/one/cluster.(Cluster).DestroyVM(0xc820187260, 0xc8203f68c0, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/provision/one/cluster/machine.go:107 +0x188
github.com/megamsys/megamd/provision/one/machine.(Machine).Remove(0xc82058f548, 0x7f05d4822b30, 0xc82011a9f0, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/provision/one/machine/machine.go:69 +0x18c
github.com/megamsys/megamd/provision/one.glob.func5(0xb7c780, 0xc8201a8380, 0xc820400910, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/provision/one/actions.go:120 +0x29f
github.com/megamsys/libgo/action.(Pipeline).Execute(0xc8203f66c0, 0xc820400910, 0x1, 0x1, 0x0, 0x0)
/home/megam/.go/src/github.com/megamsys/libgo/action/action.go:147 +0xc4c
github.com/megamsys/megamd/provision/one.(oneProvisioner).Destroy(0xc82011a9f0, 0xc820174c60, 0x7f05d0404558, 0xc8203f6640, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/provision/one/provisioner.go:187 +0x30e
github.com/megamsys/megamd/carton.Destroy(0xc82011e5f0, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/carton/destroyer.go:24 +0x344
github.com/megamsys/megamd/carton.(Carton).Destroy(0xc820262690, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/carton/carton.go:82 +0x11d
github.com/megamsys/megamd/carton.DestroyProcess.Process(0xc820185d20, 0x16, 0xc820266568, 0x1, 0x1, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/carton/megd_process.go:58 +0x74
github.com/megamsys/megamd/carton.(DestroyProcess).Process(0xc820190f70, 0xc820266568, 0x1, 0x1, 0x0, 0x0)
:7 +0xc2
github.com/megamsys/megamd/carton.(ReqOperator).Accept(0xc82058ff38, 0xc82058ff08, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/carton/req_operator.go:41 +0x1a7
github.com/megamsys/megamd/subd/deployd.(Handler).serveNSQ(0xc8201902a0, 0xc820279200, 0x0, 0x0)
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/subd/deployd/handler.go:24 +0x150
created by github.com/megamsys/megamd/subd/deployd.(*Service).processNSQ
/home/megam/code/workspace/packager/megamd/build/trusty/megamd/src/github.com/megamsys/megamd/subd/deployd/service.go:75 +0xc8

**Comment by indykish** [comment]
@ranjithamca  While you are at it, can you check this line  **opennebula-go/compute/compute.go:95**

``` golang
time="2016-01-19T15:02:23+05:30" level=debug msg="\x1b[1;34;10m > one-go SUCCESS\x1b[0m" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8579e7]

goroutine 214 [running]:
github.com/megamsys/opennebula-go/compute.(VirtualMachine).Delete(0xc82058f2a0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/megam/.go/src/github.com/megamsys/opennebula-go/compute/compute.go:95 +0x447

```

@vijaykanthm28  Please work with @ranjithamca  and close this issue.

**Comment by indykish** [comment]
This is fixed in https://github.com/megamsys/opennebula-go/pull/35
