### ISSUE TITLE
HDD is missing, when I try to create a VM

### ISSUE THREAD

**Issue by indykish** [megamsys/opennebula-go#6]
## I would like to provide CPU, Mem and HDD

@morpheyesh  
` What is Cpu ? `
`What is VCpu ?  `
``` go
type VirtualMachine struct {
	Name         string
	TemplateName string
	TemplateId   int
	Assembly_id  string
	Cpu          string
	VCpu         string
	Memory       string
	Client       *api.Rpc
}
```

**Comment by indykish** [comment]
@morpheyesh  Check this issue ? Can you clarify your thinking ? 
@thomasalrin  Check it out.

**Comment by thomasalrin** [comment]
@indykish In current version HDD can't be resized. In next release of opennebula we can get this feature
http://docs.opennebula.org/4.14/user/virtual_resource_management/vm_guide_2.html#vm-guide2-resize-disk

**Comment by morpheyesh** [comment]
@indykish CPU and VCPU is the basic VM requirements that needs to be sent from the engine

**Comment by indykish** [comment]
@morpheyesh Also why do i have have to CPU and VCPU ? What about HDD ?

**Comment by indykish** [comment]
no HDD for now.  From `megamd` we will pass VCPU and Memory only.
